before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

deploy:
  variables:
    SSHPASS: $USER_PASS
  only:
    - master
  script:
    - sshpass -e ssh kellerch@sftp.itd.umich.edu 'ls'
