image: ubuntu:18.04

before_script:
  - apt-get update -qq
  - apt-get install -y -qq ssh
  - apt-get install -y -qq sshpass

stages:
  - deploy

deploy:
  variables:
    CI_DEBUG_TRACE: "true"

  stage: deploy

  only:
    - master

  script:
    - sshpass -p $USER_PASS ssh kellerch@sftp.itd.umich.edu -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no "ls"
