image: ubuntu:18.04

before_script:
  - apt-get update -qq
  - apt-get install -y -qq ssh
  - apt-get install -y -qq sshpass

stages:
  - deploy

deploy:
  stage: deploy

  only:
    - master

  script:
    - sshpass -p $USER_PASS ssh -o StrictHostKeyChecking=no kellerch@sftp.itd.umich.edu "cd ${SITE_PATH}; ./deploy.sh"
