before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

deploy:
  variables:
    CI_DEBUG_TRACE: "true"
  only:
    - master
  script:
    - export SSHPASS=$USER_PASS
    - sshpass -e ssh kellerch@sftp.itd.umich.edu "ls"
