<?php 

/**
 * Localize Script for the custom TinyMCE buttons
 * @since FP Foundation Assistant 1.0.0
 * @version 1.1.0
 */


/*********************************************************/

add_action( "admin_head", 'fp_foundation_assistant_admin_head' );

function fp_foundation_assistant_admin_head() { ?>

<script type='text/javascript'>
var fp_foundation_assistant_localized_script = {

    'button_shortcodes': 	'<?php _e("Foundation Assistant Shortcodes","fp-foundation-assistant"); ?>',
    'icon_font': 			'<?php _e("Foundation Icon Font","fp-foundation-assistant"); ?>',
    'grid': 				'<?php _e("Grid","fp-foundation-assistant"); ?>',
    'flex_grid': 			'<?php _e("Flex Grid","fp-foundation-assistant"); ?>',
	'tabs_accordions': 		'<?php _e("Tabs & Accordions","fp-foundation-assistant"); ?>',
	'vertical_tabs': 		'<?php _e("Vertical Tabs","fp-foundation-assistant"); ?>',
	'no_of_tabs': 			'<?php _e("Number of Tabs","fp-foundation-assistant"); ?>',
	'tabs': 				'<?php _e("Tabs", "fp-foundation-assistant"); ?>',
	'tab_content': 			'<?php _e("Tab Content", "fp-foundation-assistant"); ?>',
	'none': 				'<?php _e("None","fp-foundation-assistant"); ?>',
	'one': 					'<?php _e("1","fp-foundation-assistant"); ?>',
	'two': 					'<?php _e("2", "fp-foundation-assistant"); ?>',
	'three': 				'<?php _e("3", "fp-foundation-assistant"); ?>',
	'four': 				'<?php _e("4","fp-foundation-assistant"); ?>',
	'five': 				'<?php _e("5","fp-foundation-assistant"); ?>',
	'six': 					'<?php _e("6","fp-foundation-assistant"); ?>',
	'seven': 				'<?php _e("7","fp-foundation-assistant"); ?>',
	'eight': 				'<?php _e("8", "fp-foundation-assistant"); ?>',
	'nine': 				'<?php _e("9","fp-foundation-assistant"); ?>',
	'ten': 					'<?php _e("10","fp-foundation-assistant"); ?>',
	'eleven': 				'<?php _e("11","fp-foundation-assistant"); ?>',
	'twelve': 				'<?php _e("12","fp-foundation-assistant"); ?>',
	'small': 				'<?php _e("Small","fp-foundation-assistant"); ?>',
	'medium': 				'<?php _e("Medium","fp-foundation-assistant"); ?>',
	'large': 				'<?php _e("Large","fp-foundation-assistant"); ?>',
	'xlarge': 				'<?php _e("XLarge","fp-foundation-assistant"); ?>',
	'landscape': 			'<?php _e("Landscape","fp-foundation-assistant"); ?>',
	'portrait': 			'<?php _e("Portrait","fp-foundation-assistant"); ?>',
	'small_columns': 		'<?php _e("Small Columns","fp-foundation-assistant"); ?>',
	'medium_columns': 		'<?php _e("Medium Columns","fp-foundation-assistant"); ?>',
	'large_columns': 		'<?php _e("Large Columns","fp-foundation-assistant"); ?>',
	'tabs_type':			'<?php _e("Tab Type","fp-foundation-assistant"); ?>',
	'type_vertical_tabs':	'<?php _e("Vertical","fp-foundation-assistant"); ?>',
	'type_horizontal_tabs':	'<?php _e("Horizontal","fp-foundation-assistant"); ?>',
	'accordion': 			'<?php _e("Accordion","fp-foundation-assistant"); ?>',
	'no_of_items': 			'<?php _e("Number of Items","fp-foundation-assistant"); ?>',
	'items': 				'<?php _e("Items","fp-foundation-assistant"); ?>',
	'slides': 				'<?php _e("Slides","fp-foundation-assistant"); ?>',
	'element_options': 		'<?php _e("Options","fp-foundation-assistant"); ?>',
	'basic': 				'<?php _e("Basic","fp-foundation-assistant"); ?>',
	'multiexpand': 			'<?php _e("Multi-expand","fp-foundation-assistant"); ?>', 
	'all_closed': 			'<?php _e("All Closed","fp-foundation-assistant"); ?>',
	'radius': 				'<?php _e("Radius","fp-foundation-assistant"); ?>',
	'round': 				'<?php _e("Round","fp-foundation-assistant"); ?>',
	'square': 				'<?php _e("Square","fp-foundation-assistant"); ?>',
	'element_content': 		'<?php _e("Content","fp-foundation-assistant"); ?>',
	'element_title': 		'<?php _e("Title","fp-foundation-assistant"); ?>',
	'carousel_orbit': 		'<?php _e("Orbit Carousel","fp-foundation-assistant"); ?>',
	'carousel_owl': 		'<?php _e("Owl Carousel","fp-foundation-assistant"); ?>',
	'carousels': 			'<?php _e("Carousels","fp-foundation-assistant"); ?>',
	'gutter': 				'<?php _e("Gutter","fp-foundation-assistant"); ?>',
	'place_content': 		'<?php _e("Place Content Here","fp-foundation-assistant"); ?>',
	'place_link': 			'<?php _e("http://Place Link Here","fp-foundation-assistant"); ?>',
	'embed_link': 			'<?php _e("http://Embed Link Here","fp-foundation-assistant"); ?>',
	'place_dropdown': 		'<?php _e("Do you want to insert a dropdown shortcode?","fp-foundation-assistant"); ?>', 
	'place_interchange': 	'<?php _e("Do you want to insert an interchange shortcode?","fp-foundation-assistant"); ?>', 
	'content_for_slide':	'<?php _e("Content for slide #","fp-foundation-assistant"); ?>',
	'no_gutter': 			'<?php _e("No Gutter","fp-foundation-assistant"); ?>', 
	'no_of_columns': 		'<?php _e("Number of columns","fp-foundation-assistant"); ?>',
	'expanded': 			'<?php _e("Expanded Row","fp-foundation-assistant"); ?>',
	'offsets': 				'<?php _e("Offsets","fp-foundation-assistant"); ?>',
	'source_ordering':		'<?php _e("Source Ordering","fp-foundation-assistant"); ?>',
	'block_grids':			'<?php _e("Block Grids","fp-foundation-assistant"); ?>',
	'row_equalizer':		'<?php _e("Row Equalizer","fp-foundation-assistant"); ?>',
	'equalizer':			'<?php _e("Equalizer","fp-foundation-assistant"); ?>',
	'small_un_collapse':	'<?php _e("Small Collapse / Uncollapse Row","fp-foundation-assistant"); ?>',
	'medium_un_collapse':	'<?php _e("Medium Collapse / Uncollapse Row","fp-foundation-assistant"); ?>',
	'large_un_collapse':	'<?php _e("Large Collapse / Uncollapse Row","fp-foundation-assistant"); ?>',
	'collapse':				'<?php _e("Collapse","fp-foundation-assistant"); ?>',
	'small_collapse':		'<?php _e("Small Collapse","fp-foundation-assistant"); ?>',
	'medium_collapse':		'<?php _e("Medium Collapse","fp-foundation-assistant"); ?>',
	'large_collapse':		'<?php _e("Large Collapse","fp-foundation-assistant"); ?>',
	'small_uncollapse':		'<?php _e("Small Uncollapse","fp-foundation-assistant"); ?>',
	'medium_uncollapse':	'<?php _e("Medium Uncollapse","fp-foundation-assistant"); ?>',
	'large_uncollapse':		'<?php _e("Large Uncollapse","fp-foundation-assistant"); ?>',
	'small_un_centered':	'<?php _e("Small Centered / Uncentered Row","fp-foundation-assistant"); ?>',
	'medium_un_centered':	'<?php _e("Medium Centered / Uncentered Row","fp-foundation-assistant"); ?>',
	'large_un_centered':	'<?php _e("Large Centered / Uncentered Row","fp-foundation-assistant"); ?>',
	'centered':				'<?php _e("Centered","fp-foundation-assistant"); ?>',
	'small_centered':		'<?php _e("Small Centered","fp-foundation-assistant"); ?>',
	'medium_centered':		'<?php _e("Medium Centered","fp-foundation-assistant"); ?>',
	'large_centered':		'<?php _e("Large Centered","fp-foundation-assistant"); ?>',
	'small_uncentered':		'<?php _e("Small Uncentered","fp-foundation-assistant"); ?>',
	'medium_uncentered':	'<?php _e("Medium Uncentered","fp-foundation-assistant"); ?>',
	'large_uncentered':		'<?php _e("Large Uncentered","fp-foundation-assistant"); ?>',
	'element_float':		'<?php _e("Float","fp-foundation-assistant"); ?>',
	'float_classes':		'<?php _e("Float Classes","fp-foundation-assistant"); ?>',
	'float_left':			'<?php _e("Float Left","fp-foundation-assistant"); ?>',
	'float_right':			'<?php _e("Float Right","fp-foundation-assistant"); ?>',
	'float_center':			'<?php _e("Float Center","fp-foundation-assistant"); ?>',
	'visibility_classes':	'<?php _e("Visibility Classes","fp-foundation-assistant"); ?>',
	'orientation':			'<?php _e("Orientation Classes","fp-foundation-assistant"); ?>',
	'small_visibility':		'<?php _e("Small Visibility Classes","fp-foundation-assistant"); ?>',
	'medium_visibility':	'<?php _e("Medium Visibility Classes","fp-foundation-assistant"); ?>',
	'large_visibility':		'<?php _e("Large Visibility Classes","fp-foundation-assistant"); ?>',
	'xlarge_visibility':	'<?php _e("Extra Large Visibility Classes","fp-foundation-assistant"); ?>',
	'portrait_visibility':	'<?php _e("Portrait Visibility Classes","fp-foundation-assistant"); ?>',
	'landscape_visibility':	'<?php _e("Landscape Visibility Classes","fp-foundation-assistant"); ?>',
	'accessibility':		'<?php _e("Accessibility Classes","fp-foundation-assistant"); ?>',
	'show_small': 			'<?php _e("Show on small screen size","fp-foundation-assistant"); ?>', 
	'show_medium': 			'<?php _e("Show on medium screen size","fp-foundation-assistant"); ?>', 
	'show_medium_down': 	'<?php _e("Show on medium and small screen size","fp-foundation-assistant"); ?>', 
	'show_large': 			'<?php _e("Show on large screen size","fp-foundation-assistant"); ?>', 
	'show_xlarge': 			'<?php _e("Show on x large screen size","fp-foundation-assistant"); ?>', 
	'show_xxlarge': 		'<?php _e("Show on xx large screen size","fp-foundation-assistant"); ?>', 
	'show_portrait': 		'<?php _e("Show on portrait screen size","fp-foundation-assistant"); ?>', 
	'show_landscape': 		'<?php _e("Show on landscape screen size","fp-foundation-assistant"); ?>', 
	'show_small_only': 		'<?php _e("Show only on small screen size","fp-foundation-assistant"); ?>', 
	'show_medium_only': 	'<?php _e("Show only on medium screen size","fp-foundation-assistant"); ?>', 
	'show_large_only': 		'<?php _e("Show only on large screen size","fp-foundation-assistant"); ?>', 
	'show_xlarge_only': 	'<?php _e("Show only on x large screen size","fp-foundation-assistant"); ?>', 	
	'hide_small': 			'<?php _e("Hide on small screen size","fp-foundation-assistant"); ?>', 
	'hide_medium': 			'<?php _e("Hide on medium screen size","fp-foundation-assistant"); ?>', 
	'hide_medium_down': 	'<?php _e("Hide on medium and small screen size","fp-foundation-assistant"); ?>', 
	'hide_large': 			'<?php _e("Hide on large screen size","fp-foundation-assistant"); ?>', 
	'hide_xlarge': 			'<?php _e("Hide on x large screen size","fp-foundation-assistant"); ?>', 
	'hide_xxlarge': 		'<?php _e("Hide on xx large screen size","fp-foundation-assistant"); ?>', 
	'hide_small_only': 		'<?php _e("Hide only on small screen size","fp-foundation-assistant"); ?>', 
	'hide_medium_only': 	'<?php _e("Hide only on medium screen size","fp-foundation-assistant"); ?>', 
	'hide_large_only': 		'<?php _e("Hide only on large screen size","fp-foundation-assistant"); ?>', 
	'hide_xlarge_only': 	'<?php _e("Hide only on x large screen size","fp-foundation-assistant"); ?>', 
	'hide_portrait': 		'<?php _e("Hide on portrait screen size","fp-foundation-assistant"); ?>', 
	'hide_landscape': 		'<?php _e("Hide on landscape screen size","fp-foundation-assistant"); ?>', 
	'show_sr': 				'<?php _e("Show for screen readers","fp-foundation-assistant"); ?>', 
	'menus': 				'<?php _e("Menus","fp-foundation-assistant"); ?>',
	'menu': 				'<?php _e("Menu","fp-foundation-assistant"); ?>',
	'menu_item': 			'<?php _e("Menu Item","fp-foundation-assistant"); ?>',
	'submenu_item': 		'<?php _e("Submenu Item","fp-foundation-assistant"); ?>',
	'menu_type': 			'<?php _e("Menu Type","fp-foundation-assistant"); ?>',
	'nested_menu':			'<?php _e("Nested Menu","fp-foundation-assistant"); ?>',
	'basic_menu': 			'<?php _e("Basic Menu","fp-foundation-assistant"); ?>',
	'vertical_menu': 		'<?php _e("Vertical Menu","fp-foundation-assistant"); ?>',	
	'accordion_menu': 		'<?php _e("Accordion Menu","fp-foundation-assistant"); ?>',
	'dropdown_menu': 		'<?php _e("Dropdown Menu","fp-foundation-assistant"); ?>',
	'drilldown_menu': 		'<?php _e("Drilldown Menu","fp-foundation-assistant"); ?>',
	'foundation_elements': 	'<?php _e("Elements","fp-foundation-assistant"); ?>',
	'foundation_default': 	'<?php _e("Default","fp-foundation-assistant"); ?>',
	'closable': 			'<?php _e("Closable","fp-foundation-assistant"); ?>',
	'position_top': 		'<?php _e("Top","fp-foundation-assistant"); ?>',
	'position_right': 		'<?php _e("Right","fp-foundation-assistant"); ?>',
	'position_left': 		'<?php _e("Left","fp-foundation-assistant"); ?>',
	'position_bottom': 		'<?php _e("Bottom","fp-foundation-assistant"); ?>',
	'boxes': 				'<?php _e("Boxes","fp-foundation-assistant"); ?>',
	'presentation_boxes': 	'<?php _e("Presentation Boxes","fp-foundation-assistant"); ?>',
	'layout': 				'<?php _e("Layout","fp-foundation-assistant"); ?>',
	'image_for_box': 		'<?php _e("Image for box #","fp-foundation-assistant"); ?>',
	'title_for_box': 		'<?php _e("Title for box #","fp-foundation-assistant"); ?>',
	'text_for_box': 		'<?php _e("Text for box #","fp-foundation-assistant"); ?>',
	'carousel_boxes': 		'<?php _e("Carousel Boxes","fp-foundation-assistant"); ?>',
	'typography': 			'<?php _e("Typography","fp-foundation-assistant"); ?>',
	'lists': 				'<?php _e("Lists","fp-foundation-assistant"); ?>',
	'element_type': 		'<?php _e("Type","fp-foundation-assistant"); ?>', 
	'unordered_list': 		'<?php _e("Unordered List","fp-foundation-assistant"); ?>', 
	'ordered_list': 		'<?php _e("Ordered List","fp-foundation-assistant"); ?>',
	'description_list': 	'<?php _e("Description List","fp-foundation-assistant"); ?>', 
	'element_style': 		'<?php _e("Style","fp-foundation-assistant"); ?>',
	'list_item': 			'<?php _e("List Item #","fp-foundation-assistant"); ?>',
	'description_for_item':	'<?php _e("Description for Item #","fp-foundation-assistant"); ?>',
	'blockquotes': 			'<?php _e("Blockquotes","fp-foundation-assistant"); ?>',
	'quote_text': 			'<?php _e("Quote Text","fp-foundation-assistant"); ?>',
	'dividers': 			'<?php _e("Dividers","fp-foundation-assistant"); ?>',
	'containers': 			'<?php _e("Containers","fp-foundation-assistant"); ?>',
	'callout': 				'<?php _e("Callout","fp-foundation-assistant"); ?>',
	'standard': 			'<?php _e("Standard","fp-foundation-assistant"); ?>', 
	'primary': 				'<?php _e("Primary","fp-foundation-assistant"); ?>', 
	'secondary': 			'<?php _e("Secondary","fp-foundation-assistant"); ?>', 
	'primary': 				'<?php _e("Primary","fp-foundation-assistant"); ?>', 
	'success': 				'<?php _e("Success","fp-foundation-assistant"); ?>',
	'warning': 				'<?php _e("Warning","fp-foundation-assistant"); ?>',
	'alert': 				'<?php _e("Alert","fp-foundation-assistant"); ?>',
	'callout_message': 		'<?php _e("Callout Message","fp-foundation-assistant"); ?>',
	'badge': 				'<?php _e("Badge","fp-foundation-assistant"); ?>',
	'theme_accent': 		'<?php _e("Theme Accent","fp-foundation-assistant"); ?>', 
	'style_info': 			'<?php _e("Info","fp-foundation-assistant"); ?>', 
	'b': 					'<?php _e("B","fp-foundation-assistant"); ?>',
	'buttons': 				'<?php _e("Buttons","fp-foundation-assistant"); ?>',
	'element_button': 		'<?php _e("Button","fp-foundation-assistant"); ?>',
	'element_link': 		'<?php _e("Link","fp-foundation-assistant"); ?>',
	'element_size': 		'<?php _e("Size","fp-foundation-assistant"); ?>', 	
	'element_color': 		'<?php _e("Color","fp-foundation-assistant"); ?>', 
	'element_shape': 		'<?php _e("Shape","fp-foundation-assistant"); ?>', 
	'element_position': 	'<?php _e("Position","fp-foundation-assistant"); ?>',  
	'element_width': 		'<?php _e("Width","fp-foundation-assistant"); ?>', 
	'element_height': 		'<?php _e("Height","fp-foundation-assistant"); ?>', 
	'element_image': 		'<?php _e("Image","fp-foundation-assistant"); ?>',
	'element_html': 		'<?php _e("HTML","fp-foundation-assistant"); ?>',	
	'element_label': 		'<?php _e("Label","fp-foundation-assistant"); ?>',	
	'element_submit': 		'<?php _e("Submit","fp-foundation-assistant"); ?>',	
	'element_reset': 		'<?php _e("Reset","fp-foundation-assistant"); ?>',	
	'new_tab': 				'<?php _e("New Tab for Links","fp-foundation-assistant"); ?>',		
	'tiny': 				'<?php _e("Tiny","fp-foundation-assistant"); ?>', 
	'small': 				'<?php _e("Small","fp-foundation-assistant"); ?>',
	'large': 				'<?php _e("Large","fp-foundation-assistant"); ?>',
	'full': 				'<?php _e("Full","fp-foundation-assistant"); ?>',
	'expanded': 			'<?php _e("Expanded","fp-foundation-assistant"); ?>',
	'expand': 				'<?php _e("Expand","fp-foundation-assistant"); ?>',
	'small_expanded': 		'<?php _e("Small Expanded","fp-foundation-assistant"); ?>',
	'style_disabled': 		'<?php _e("Disabled","fp-foundation-assistant"); ?>', 
	'dropdown': 			'<?php _e("Dropdown","fp-foundation-assistant"); ?>', 	
	'split': 				'<?php _e("Split","fp-foundation-assistant"); ?>', 
	'hollow': 				'<?php _e("Hollow","fp-foundation-assistant"); ?>', 
	'hollow_standard': 		'<?php _e("Hollow Standard","fp-foundation-assistant"); ?>', 
	'hollow_theme_accent': 	'<?php _e("Hollow Theme Accent","fp-foundation-assistant"); ?>', 
	'hallow_secondary': 	'<?php _e("Hollow Secondary","fp-foundation-assistant"); ?>', 
	'hollow_success': 		'<?php _e("Hollow Success","fp-foundation-assistant"); ?>', 
	'hollow_warning': 		'<?php _e("Hollow Warning","fp-foundation-assistant"); ?>',
	'hollow_disabled': 		'<?php _e("Hollow Disabled","fp-foundation-assistant"); ?>',
	'flex_video': 			'<?php _e("Flex Video","fp-foundation-assistant"); ?>', 
	'widescreen': 			'<?php _e("Widescreen","fp-foundation-assistant"); ?>', 
	'vimeo': 				'<?php _e("Vimeo","fp-foundation-assistant"); ?>',
	'interchange': 			'<?php _e("Interchange","fp-foundation-assistant"); ?>',
	'progress': 			'<?php _e("Progress","fp-foundation-assistant"); ?>',
	'reveal': 				'<?php _e("Reveal","fp-foundation-assistant"); ?>',
	'overlay': 				'<?php _e("No overlay","fp-foundation-assistant"); ?>',
	'tooltip': 				'<?php _e("Tooltip","fp-foundation-assistant"); ?>',
	'hover': 				'<?php _e("Hover","fp-foundation-assistant"); ?>',
	'responsive_adjustments':'<?php _e("Responsive Adjustments","fp-foundation-assistant"); ?>',
	'element_align': 		'<?php _e("Align","fp-foundation-assistant"); ?>',
	'horizontal_align': 	'<?php _e("Horizontal Align","fp-foundation-assistant"); ?>',
	'vertical_align': 		'<?php _e("Vertical Align","fp-foundation-assistant"); ?>',
	'align_right': 			'<?php _e("Right","fp-foundation-assistant"); ?>',
	'align_left': 			'<?php _e("Left","fp-foundation-assistant"); ?>',
	'align_center': 		'<?php _e("Center","fp-foundation-assistant"); ?>',
	'align_justify': 		'<?php _e("Justify","fp-foundation-assistant"); ?>',
	'align_spaced': 		'<?php _e("Spaced","fp-foundation-assistant"); ?>',
	'align_top': 			'<?php _e("Top","fp-foundation-assistant"); ?>',
	'align_middle': 		'<?php _e("Middle","fp-foundation-assistant"); ?>',
	'align_bottom': 		'<?php _e("Bottom","fp-foundation-assistant"); ?>',
	'align_stretch': 		'<?php _e("Stretch","fp-foundation-assistant"); ?>',	
	'medium_expand': 		'<?php _e("Medium Expand","fp-foundation-assistant"); ?>',	
	'large_expand': 		'<?php _e("Large Expand","fp-foundation-assistant"); ?>',	
	'medium_unstack': 		'<?php _e("Medium Unstack","fp-foundation-assistant"); ?>',
	'large_unstack': 		'<?php _e("Large Unstack","fp-foundation-assistant"); ?>',
	'shrink': 				'<?php _e("Shrink","fp-foundation-assistant"); ?>',
	'post_query': 			'<?php _e("Query","fp-foundation-assistant"); ?>',
	'post_number': 			'<?php _e("Number of posts to display","fp-foundation-assistant"); ?>',
	'post_sticky': 			'<?php _e("Ignore sticky posts","fp-foundation-assistant"); ?>',
	'post_cat': 			'<?php _e("Display posts by category slug","fp-foundation-assistant"); ?>',
	'post_tag': 			'<?php _e("Display posts by tags","fp-foundation-assistant"); ?>',
	'post_type': 			'<?php _e("Display posts by post type","fp-foundation-assistant"); ?>',
	'display_title': 		'<?php _e("Don\'t display the title","fp-foundation-assistant"); ?>',
	'display_date': 		'<?php _e("Don\'t display the date","fp-foundation-assistant"); ?>',
	'display_cat': 			'<?php _e("Don\'t display the cat","fp-foundation-assistant"); ?>',
	'display_tags': 		'<?php _e("Don\'t display the tags","fp-foundation-assistant"); ?>',
	'display_author': 		'<?php _e("Don\'t display the author","fp-foundation-assistant"); ?>',
	'display_excerpt': 		'<?php _e("Don\'t display the excerpt","fp-foundation-assistant"); ?>',
	'display_thumb': 		'<?php _e("Don\'t display the thumbnail","fp-foundation-assistant"); ?>',
	'display_comments': 	'<?php _e("Don\'t display the comments","fp-foundation-assistant"); ?>',
	'display_carousel': 	'<?php _e("Display in a carousel","fp-foundation-assistant"); ?>',
	'post_wp_query': 		'<?php _e("The shortcode accepts all parameters from the WP_Query.","fp-foundation-assistant"); ?>',
	'post_wp_doc': 			'<?php _e("Read the documentation for more information.","fp-foundation-assistant"); ?>',
	'fi_zoom_out': 			'<?php _e("Zoom Out","fp-foundation-assistant"); ?>',
	'fi_zoom_in': 			'<?php _e("Zoom In","fp-foundation-assistant"); ?>',
	'fi_yen': 				'<?php _e("Yen","fp-foundation-assistant"); ?>',
	'fi_x': 				'<?php _e("X","fp-foundation-assistant"); ?>',
	'fi_x_circle': 			'<?php _e("X Circle","fp-foundation-assistant"); ?>',
	'fi_wrench': 			'<?php _e("Wrench","fp-foundation-assistant"); ?>',
	'fi_widget': 			'<?php _e("Widget","fp-foundation-assistant"); ?>',
	'fi_wheelchair': 		'<?php _e("Wheelchair","fp-foundation-assistant"); ?>',
	'fi_web': 				'<?php _e("Web","fp-foundation-assistant"); ?>',
	'fi_volume':       		'<?php _e("Volume","fp-foundation-assistant"); ?>',
	'fi_volume_strike': 	'<?php _e("Volume Strike","fp-foundation-assistant"); ?>',
	'fi_volume_none': 		'<?php _e("Volume None","fp-foundation-assistant"); ?>',
	'fi_video': 			'<?php _e("Video","fp-foundation-assistant"); ?>',
	'fi_usb': 				'<?php _e("USB","fp-foundation-assistant"); ?>',
	'fi_upload': 			'<?php _e("Upload","fp-foundation-assistant"); ?>',
	'fi_upload_cloud': 		'<?php _e("Upload Cloud","fp-foundation-assistant"); ?>',
	'fi_unlock': 			'<?php _e("Unlock","fp-foundation-assistant"); ?>',
	'fi_unlink': 			'<?php _e("Unlink","fp-foundation-assistant"); ?>',
	'fi_universal_access': 	'<?php _e("Universal Access","fp-foundation-assistant"); ?>',
	'fi_underline': 		'<?php _e("Underline","fp-foundation-assistant"); ?>',
	'fi_trophy': 			'<?php _e("Trophy","fp-foundation-assistant"); ?>',
	'fi_trees': 			'<?php _e("Trees","fp-foundation-assistant"); ?>',
	'fi_trash': 			'<?php _e("Trash","fp-foundation-assistant"); ?>',
	'fi_torsos': 			'<?php _e("Torsos","fp-foundation-assistant"); ?>',
	'fi_torsos_male_female':'<?php _e("Torsos Male Female","fp-foundation-assistant"); ?>',
	'fi_torsos_female_male':'<?php _e("Torsos Female Male","fp-foundation-assistant"); ?>',
	'fi_torsos_all': 		'<?php _e("Torsos All","fp-foundation-assistant"); ?>',
	'fi_torsos_all_female': '<?php _e("Torsos All Female","fp-foundation-assistant"); ?>',
	'fi_torso': 			'<?php _e("Torso","fp-foundation-assistant"); ?>',
	'fi_torso_female': 		'<?php _e("Torso Female","fp-foundation-assistant"); ?>',
	'fi_torso_business': 	'<?php _e("Torso Business","fp-foundation-assistant"); ?>',
	'fi_ticket': 			'<?php _e("Ticket","fp-foundation-assistant"); ?>',
	'fi_thumbnails': 		'<?php _e("Thumbnails","fp-foundation-assistant"); ?>',
	'fi_text_color': 		'<?php _e("Text Color","fp-foundation-assistant"); ?>',
	'fi_telephone': 		'<?php _e("Telephone","fp-foundation-assistant"); ?>',
	'fi_telephone_access':  '<?php _e("Telephone Accessible","fp-foundation-assistant"); ?>',
	'fi_target': 			'<?php _e("Target","fp-foundation-assistant"); ?>',
	'fi_target_two': 		'<?php _e("Target Two","fp-foundation-assistant"); ?>',
	'fi_tablet_portrait': 	'<?php _e("Tablet Portrait","fp-foundation-assistant"); ?>',
	'fi_tablet_landscape': 	'<?php _e("Tablet Landscape","fp-foundation-assistant"); ?>',
	'fi_superscript': 		'<?php _e("Superscript","fp-foundation-assistant"); ?>',
	'fi_subscript': 		'<?php _e("Subscript","fp-foundation-assistant"); ?>',
	'fi_strikethrough': 	'<?php _e("Strikethrough","fp-foundation-assistant"); ?>',
	'fi_stop': 				'<?php _e("Stop","fp-foundation-assistant"); ?>',
	'fi_star': 				'<?php _e("Star","fp-foundation-assistant"); ?>',
	'fi_sound': 			'<?php _e("Sound","fp-foundation-assistant"); ?>',
	'fi_social_zurb': 		'<?php _e("Social Zurb","fp-foundation-assistant"); ?>',
	'fi_social_zerply': 	'<?php _e("Social Zerply","fp-foundation-assistant"); ?>',
	'fi_social_youtube': 	'<?php _e("Social Youtube","fp-foundation-assistant"); ?>',
	'fi_social_yelp': 		'<?php _e("Social Yelp","fp-foundation-assistant"); ?>',
	'fi_social_yahoo': 		'<?php _e("Social Yahoo","fp-foundation-assistant"); ?>',
	'fi_social_xbox': 		'<?php _e("Social Xbox","fp-foundation-assistant"); ?>',
	'fi_social_windows': 	'<?php _e("Social Windows","fp-foundation-assistant"); ?>',
	'fi_social_vimeo': 		'<?php _e("Social Vimeo","fp-foundation-assistant"); ?>',
	'fi_social_twitter': 	'<?php _e("Social Twitter","fp-foundation-assistant"); ?>',
	'fi_social_tumblr': 	'<?php _e("Social Tumblr","fp-foundation-assistant"); ?>',
	'fi_social_treehouse': 	'<?php _e("Social Treehouse","fp-foundation-assistant"); ?>',
	'fi_social_stumbleupon':'<?php _e("Social Stumbleupon","fp-foundation-assistant"); ?>',
	'fi_social_steam': 		'<?php _e("Social Steam","fp-foundation-assistant"); ?>',
	'fi_social_stack_over': '<?php _e("Social Stack Overflow","fp-foundation-assistant"); ?>',
	'fi_social_squidoo': 	'<?php _e("Social Squidoo","fp-foundation-assistant"); ?>',
	'fi_social_spotify': 	'<?php _e("Social Spotify","fp-foundation-assistant"); ?>',
	'fi_social_snapchat': 	'<?php _e("Social Snapchat","fp-foundation-assistant"); ?>',
	'fi_social_smashing':   '<?php _e("Social Smashing Mag","fp-foundation-assistant"); ?>',
	'fi_social_skype': 		'<?php _e("Social Skype","fp-foundation-assistant"); ?>',
	'fi_social_skillshare': '<?php _e("Social Skillshare","fp-foundation-assistant"); ?>',
	'fi_social_reddit': 	'<?php _e("Social Reddit","fp-foundation-assistant"); ?>',
	'fi_social_rdio': 		'<?php _e("Social Rdio","fp-foundation-assistant"); ?>',
	'fi_social_pinterest': 	'<?php _e("Social Pinterest","fp-foundation-assistant"); ?>',
	'fi_social_picasa': 	'<?php _e("Social Picasa","fp-foundation-assistant"); ?>',
	'fi_social_path':      	'<?php _e("Social Path","fp-foundation-assistant"); ?>',
	'fi_social_orkut': 		'<?php _e("Social Orkut","fp-foundation-assistant"); ?>',
	'fi_social_myspace': 	'<?php _e("Social Myspace","fp-foundation-assistant"); ?>',
	'fi_social_medium': 	'<?php _e("Social Medium","fp-foundation-assistant"); ?>',
	'fi_social_linkedin': 	'<?php _e("Social Linkedin","fp-foundation-assistant"); ?>',
	'fi_social_lastfm': 	'<?php _e("Social Lastfm","fp-foundation-assistant"); ?>',
	'fi_social_joomla': 	'<?php _e("Social Joomla","fp-foundation-assistant"); ?>',
	'fi_social_instagram': 	'<?php _e("Social Instagram","fp-foundation-assistant"); ?>',
	'fi_social_hi5': 		'<?php _e("Social hi5","fp-foundation-assistant"); ?>',
	'fi_social_hacker_news':'<?php _e("Social Hacker News","fp-foundation-assistant"); ?>',
	'fi_social_google_plus':'<?php _e("Social Google Plus","fp-foundation-assistant"); ?>',
	'fi_social_github': 	'<?php _e("Social Github","fp-foundation-assistant"); ?>',
	'fi_social_game_center':'<?php _e("Social Game Center","fp-foundation-assistant"); ?>',
	'fi_social_foursquare': '<?php _e("Social Foursquare","fp-foundation-assistant"); ?>',
	'fi_social_forrst': 	'<?php _e("Social Forrst","fp-foundation-assistant"); ?>',
	'fi_social_flickr': 	'<?php _e("Social Flickr","fp-foundation-assistant"); ?>',
	'fi_social_facebook': 	'<?php _e("Social Facebook","fp-foundation-assistant"); ?>',
	'fi_social_evernote': 	'<?php _e("Social Evernote","fp-foundation-assistant"); ?>',
	'fi_social_dropbox': 	'<?php _e("Social Dropbox","fp-foundation-assistant"); ?>',
	'fi_social_drive': 		'<?php _e("Social Drive","fp-foundation-assistant"); ?>',
	'fi_social_dribbble': 	'<?php _e("Social Dribbble","fp-foundation-assistant"); ?>',
	'fi_social_digg': 		'<?php _e("Social Digg","fp-foundation-assistant"); ?>',
	'fi_social_deviant_art':'<?php _e("Social Deviant Art","fp-foundation-assistant"); ?>',
	'fi_social_designer': 	'<?php _e("Social Designer News","fp-foundation-assistant"); ?>',
	'fi_social_delicious': 	'<?php _e("Social Delicious","fp-foundation-assistant"); ?>',
	'fi_social_blogger': 	'<?php _e("Social Blogger","fp-foundation-assistant"); ?>',
	'fi_social_bing': 		'<?php _e("Social Bing","fp-foundation-assistant"); ?>',
	'fi_social_behance': 	'<?php _e("Social Behance","fp-foundation-assistant"); ?>',
	'fi_social_apple': 		'<?php _e("Social Apple","fp-foundation-assistant"); ?>',
	'fi_social_android': 	'<?php _e("Social Android","fp-foundation-assistant"); ?>',
	'fi_social_amazon': 	'<?php _e("Social Amazon","fp-foundation-assistant"); ?>',
	'fi_social_adobe': 		'<?php _e("Social Adobe","fp-foundation-assistant"); ?>',
	'fi_social_500px': 		'<?php _e("Social 500px","fp-foundation-assistant"); ?>',
	'fi_skull': 			'<?php _e("Skull","fp-foundation-assistant"); ?>',
	'fi_shuffle': 			'<?php _e("Shuffle","fp-foundation-assistant"); ?>',
	'fi_shopping_cart': 	'<?php _e("Shopping Cart","fp-foundation-assistant"); ?>',
	'fi_shopping_bag': 		'<?php _e("Shopping Bag","fp-foundation-assistant"); ?>',
	'fi_shield': 			'<?php _e("Shield","fp-foundation-assistant"); ?>',
	'fi_sheriff_badge': 	'<?php _e("Sheriff Badge","fp-foundation-assistant"); ?>',
	'fi_share': 			'<?php _e("Share","fp-foundation-assistant"); ?>',
	'fi_save': 				'<?php _e("Save","fp-foundation-assistant"); ?>',
	'fi_safety_cone': 		'<?php _e("Safety Cone","fp-foundation-assistant"); ?>',
	'fi_rss': 				'<?php _e("RSS","fp-foundation-assistant"); ?>',
	'fi_rewind': 			'<?php _e("Rewind","fp-foundation-assistant"); ?>',
	'fi_rewind_ten': 		'<?php _e("Rewind Ten","fp-foundation-assistant"); ?>',
	'fi_results': 			'<?php _e("Results","fp-foundation-assistant"); ?>',
	'fi_results_demo':    	'<?php _e("Results Demographics","fp-foundation-assistant"); ?>',
	'fi_refresh': 			'<?php _e("Refresh","fp-foundation-assistant"); ?>',
	'fi_record': 			'<?php _e("Record","fp-foundation-assistant"); ?>',
	'fi_puzzle': 			'<?php _e("Puzzle","fp-foundation-assistant"); ?>',
	'fi_projection_screen': '<?php _e("Projection Screen","fp-foundation-assistant"); ?>',
	'fi_prohibited': 		'<?php _e("Prohibited","fp-foundation-assistant"); ?>',
	'fi_print': 			'<?php _e("Print","fp-foundation-assistant"); ?>',
	'fi_pricetag_multiple': '<?php _e("Pricetag Multiple","fp-foundation-assistant"); ?>',
	'fi_price_tag': 		'<?php _e("Price Tag","fp-foundation-assistant"); ?>',
	'fi_previous': 			'<?php _e("Previous","fp-foundation-assistant"); ?>',
	'fi_power': 			'<?php _e("Power","fp-foundation-assistant"); ?>',
	'fi_pound': 			'<?php _e("Pound","fp-foundation-assistant"); ?>',
	'fi_plus': 				'<?php _e("Plus","fp-foundation-assistant"); ?>',
	'fi_play': 				'<?php _e("Play","fp-foundation-assistant"); ?>',
	'fi_play_video': 		'<?php _e("Play Video","fp-foundation-assistant"); ?>',
	'fi_play_circle': 		'<?php _e("Play Circle","fp-foundation-assistant"); ?>',
	'fi_photo': 			'<?php _e("Photo","fp-foundation-assistant"); ?>',
	'fi_pencil': 			'<?php _e("Pencil","fp-foundation-assistant"); ?>',
	'fi_paypal': 			'<?php _e("Paypal","fp-foundation-assistant"); ?>',
	'fi_paw': 				'<?php _e("Paw","fp-foundation-assistant"); ?>',
	'fi_pause': 			'<?php _e("Pause","fp-foundation-assistant"); ?>',
	'fi_paperclip': 		'<?php _e("Paperclip","fp-foundation-assistant"); ?>',
	'fi_paint_bucket': 		'<?php _e("Paint Bucket","fp-foundation-assistant"); ?>',
	'fi_page': 				'<?php _e("Page","fp-foundation-assistant"); ?>',
	'fi_page_search': 		'<?php _e("Page Search","fp-foundation-assistant"); ?>',
	'fi_page_remove': 		'<?php _e("Page Remove","fp-foundation-assistant"); ?>',
	'fi_page_pdf': 			'<?php _e("Page PDF","fp-foundation-assistant"); ?>',
	'fi_page_multiple': 	'<?php _e("Page Multiple","fp-foundation-assistant"); ?>',
	'fi_page_filled': 		'<?php _e("Page Filled","fp-foundation-assistant"); ?>',
	'fi_page_export': 		'<?php _e("Page Export","fp-foundation-assistant"); ?>',
	'fi_page_export_pdf': 	'<?php _e("Page Export PDF","fp-foundation-assistant"); ?>',
	'fi_page_export_doc': 	'<?php _e("Page Export Doc","fp-foundation-assistant"); ?>',
	'fi_page_export_csv': 	'<?php _e("Page Export CSV","fp-foundation-assistant"); ?>',
	'fi_page_edit': 		'<?php _e("Page Edit","fp-foundation-assistant"); ?>',
	'fi_page_doc': 			'<?php _e("Page DOC","fp-foundation-assistant"); ?>',
	'fi_page_delete': 		'<?php _e("Page Delete","fp-foundation-assistant"); ?>',
	'fi_page_csv': 			'<?php _e("Page CSV","fp-foundation-assistant"); ?>',
	'fi_page_copy': 		'<?php _e("Page Copy","fp-foundation-assistant"); ?>',
	'fi_page_add': 			'<?php _e("Page Add","fp-foundation-assistant"); ?>',
	'fi_no_smoking': 		'<?php _e("No Smoking","fp-foundation-assistant"); ?>',
	'fi_no_dogs': 			'<?php _e("No Dogs","fp-foundation-assistant"); ?>',
	'fi_next': 				'<?php _e("Next","fp-foundation-assistant"); ?>',
	'fi_music': 			'<?php _e("Music","fp-foundation-assistant"); ?>',
	'fi_mountains': 		'<?php _e("Mountains","fp-foundation-assistant"); ?>',
	'fi_monitor': 			'<?php _e("Monitor","fp-foundation-assistant"); ?>',
	'fi_mobile': 			'<?php _e("Mobile","fp-foundation-assistant"); ?>',
	'fi_mobile_signal': 	'<?php _e("Mobile Signal","fp-foundation-assistant"); ?>',
	'fi_minus': 			'<?php _e("Minus","fp-foundation-assistant"); ?>',
	'fi_minus_circle': 		'<?php _e("Minus Circle","fp-foundation-assistant"); ?>',
	'fi_microphone': 		'<?php _e("Microphone","fp-foundation-assistant"); ?>',
	'fi_megaphone': 		'<?php _e("Megaphone","fp-foundation-assistant"); ?>',
	'fi_marker': 			'<?php _e("Marker","fp-foundation-assistant"); ?>',
	'fi_map': 				'<?php _e("Map","fp-foundation-assistant"); ?>',
	'fi_male': 		      	'<?php _e("Male","fp-foundation-assistant"); ?>',
	'fi_male_symbol': 		'<?php _e("Male Symbol","fp-foundation-assistant"); ?>',
	'fi_male_female': 		'<?php _e("Male Female","fp-foundation-assistant"); ?>',
	'fi_mail': 		        '<?php _e("Mail","fp-foundation-assistant"); ?>',
	'fi_magnifying_glass': 	'<?php _e("Magnifying Glass","fp-foundation-assistant"); ?>',
	'fi_loop': 				'<?php _e("Loop","fp-foundation-assistant"); ?>',
	'fi_lock': 				'<?php _e("Lock","fp-foundation-assistant"); ?>',
	'fi_list': 				'<?php _e("List","fp-foundation-assistant"); ?>',
	'fi_list_thumbnails': 	'<?php _e("List Thumbnails","fp-foundation-assistant"); ?>',
	'fi_list_number': 		'<?php _e("List Number","fp-foundation-assistant"); ?>',
	'fi_list_bullet': 		'<?php _e("List Bullet","fp-foundation-assistant"); ?>',
	'fi_link': 				'<?php _e("Link","fp-foundation-assistant"); ?>',
	'fi_like': 				'<?php _e("Like","fp-foundation-assistant"); ?>',
	'fi_lightbulb': 		'<?php _e("Lightbulb","fp-foundation-assistant"); ?>',
	'fi_layout': 			'<?php _e("Layout","fp-foundation-assistant"); ?>',
	'fi_laptop': 			'<?php _e("Laptop","fp-foundation-assistant"); ?>',
	'fi_key': 				'<?php _e("Key","fp-foundation-assistant"); ?>',
	'fi_italic': 			'<?php _e("Italic","fp-foundation-assistant"); ?>',
	'fi_info': 				'<?php _e("Info","fp-foundation-assistant"); ?>',
	'fi_indent_more': 		'<?php _e("Indent More","fp-foundation-assistant"); ?>',
	'fi_indent_less': 		'<?php _e("Indent Less","fp-foundation-assistant"); ?>',
	'fi_html5': 			'<?php _e("HTML5","fp-foundation-assistant"); ?>',
	'fi_home': 				'<?php _e("Home","fp-foundation-assistant"); ?>',
	'fi_heart': 			'<?php _e("Heart","fp-foundation-assistant"); ?>',
	'fi_hearing_aid': 		'<?php _e("Hearing Aid","fp-foundation-assistant"); ?>',
	'fi_guide_dog': 		'<?php _e("Guide Dog","fp-foundation-assistant"); ?>',
	'fi_graph_trend': 		'<?php _e("Graph Trend","fp-foundation-assistant"); ?>',
	'fi_graph_pie': 		'<?php _e("Graph Pie","fp-foundation-assistant"); ?>',
	'fi_graph_horizontal': 	'<?php _e("Graph Horizontal","fp-foundation-assistant"); ?>',
	'fi_graph_bar': 		'<?php _e("Graph Bar","fp-foundation-assistant"); ?>',
	'fi_foundation': 		'<?php _e("Foundation","fp-foundation-assistant"); ?>',
	'fi_foot': 				'<?php _e("Foot","fp-foundation-assistant"); ?>',
	'fi_folder': 			'<?php _e("Folder","fp-foundation-assistant"); ?>',
	'fi_folder_lock': 		'<?php _e("Folder Lock","fp-foundation-assistant"); ?>',
	'fi_folder_add': 		'<?php _e("Folder Add","fp-foundation-assistant"); ?>',
	'fi_flag': 				'<?php _e("Flag","fp-foundation-assistant"); ?>',
	'fi_first_aid': 		'<?php _e("First Aid","fp-foundation-assistant"); ?>',
	'fi_filter': 			'<?php _e("Filter","fp-foundation-assistant"); ?>',
	'fi_female': 			'<?php _e("Female","fp-foundation-assistant"); ?>',
	'fi_female_symbol': 	'<?php _e("Female Symbol","fp-foundation-assistant"); ?>',
	'fi_fast_forward': 		'<?php _e("Fast Forward","fp-foundation-assistant"); ?>',
	'fi_eye': 				'<?php _e("Eye","fp-foundation-assistant"); ?>',
	'fi_euro': 				'<?php _e("Euro","fp-foundation-assistant"); ?>',
	'fi_elevator': 			'<?php _e("Elevator","fp-foundation-assistant"); ?>',
	'fi_eject': 			'<?php _e("Eject","fp-foundation-assistant"); ?>',
	'fi_download': 			'<?php _e("Download","fp-foundation-assistant"); ?>',
	'fi_dollar': 			'<?php _e("Dollar","fp-foundation-assistant"); ?>',
	'fi_dollar_bill': 		'<?php _e("Dollar Bill","fp-foundation-assistant"); ?>',
	'fi_dislike': 			'<?php _e("Dislike","fp-foundation-assistant"); ?>',
	'fi_die_two': 			'<?php _e("Die Two","fp-foundation-assistant"); ?>',
	'fi_die_three': 		'<?php _e("Die Three","fp-foundation-assistant"); ?>',
	'fi_die_six': 			'<?php _e("Die Six","fp-foundation-assistant"); ?>',
	'fi_die_one': 			'<?php _e("Die One","fp-foundation-assistant"); ?>',
	'fi_die_four': 			'<?php _e("Die Four","fp-foundation-assistant"); ?>',
	'fi_die_five': 			'<?php _e("Die Five","fp-foundation-assistant"); ?>',
	'fi_database': 			'<?php _e("Database","fp-foundation-assistant"); ?>',
	'fi_css3': 				'<?php _e("CSS3","fp-foundation-assistant"); ?>',
	'fi_crown': 			'<?php _e("Crown","fp-foundation-assistant"); ?>',
	'fi_crop': 				'<?php _e("Crop","fp-foundation-assistant"); ?>',
	'fi_credit_card': 		'<?php _e("Credit Card","fp-foundation-assistant"); ?>',
	'fi_contrast': 			'<?php _e("Contrast","fp-foundation-assistant"); ?>',
	'fi_compass': 			'<?php _e("Compass","fp-foundation-assistant"); ?>',
	'fi_comments': 			'<?php _e("Comments","fp-foundation-assistant"); ?>',
	'fi_comment': 			'<?php _e("Comment","fp-foundation-assistant"); ?>',
	'fi_comment_video': 	'<?php _e("Comment Video","fp-foundation-assistant"); ?>',
	'fi_comment_quotes': 	'<?php _e("Comment Quotes","fp-foundation-assistant"); ?>',
	'fi_comment_minus': 	'<?php _e("Comment Minus","fp-foundation-assistant"); ?>',
	'fi_cloud': 			'<?php _e("Cloud","fp-foundation-assistant"); ?>',
	'fi_closed_caption': 	'<?php _e("Closed Caption","fp-foundation-assistant"); ?>',
	'fi_clock': 			'<?php _e("Clock","fp-foundation-assistant"); ?>',
	'fi_clipboard': 		'<?php _e("Clipboard","fp-foundation-assistant"); ?>',
	'fi_clipboard_pencil': 	'<?php _e("Clipboard Pencil","fp-foundation-assistant"); ?>',
	'fi_clipboard_notes': 	'<?php _e("Clipboard Notes","fp-foundation-assistant"); ?>',
	'fi_checkbox': 			'<?php _e("Checkbox","fp-foundation-assistant"); ?>',
	'fi_check': 			'<?php _e("Check","fp-foundation-assistant"); ?>',
	'fi_camera': 			'<?php _e("Camera","fp-foundation-assistant"); ?>',
	'fi_calendar': 			'<?php _e("Calendar","fp-foundation-assistant"); ?>',
	'fi_burst': 			'<?php _e("Burst","fp-foundation-assistant"); ?>',
	'fi_burst_sale': 		'<?php _e("Burst Sale","fp-foundation-assistant"); ?>',
	'fi_burst_new': 		'<?php _e("Burst New","fp-foundation-assistant"); ?>',
	'fi_braille': 			'<?php _e("Braille","fp-foundation-assistant"); ?>',
	'fi_bookmark': 			'<?php _e("Bookmark","fp-foundation-assistant"); ?>',
	'fi_book': 				'<?php _e("Book","fp-foundation-assistant"); ?>',
	'fi_book_bookmark': 	'<?php _e("Book Bookmark","fp-foundation-assistant"); ?>',
	'fi_bold': 				'<?php _e("Bold","fp-foundation-assistant"); ?>',
	'fi_bluetooth': 		'<?php _e("Bluetooth","fp-foundation-assistant"); ?>',
	'fi_blind': 			'<?php _e("Blind","fp-foundation-assistant"); ?>',
	'fi_bitcoin': 			'<?php _e("Bitcoin","fp-foundation-assistant"); ?>',
	'fi_bitcoin_circle': 	'<?php _e("Bitcoin-circle","fp-foundation-assistant"); ?>',
	'fi_battery_empty': 	'<?php _e("Battery Empty","fp-foundation-assistant"); ?>',
	'fi_battery_half': 		'<?php _e("Battery Half","fp-foundation-assistant"); ?>',
	'fi_battery_full': 		'<?php _e("Battery Full","fp-foundation-assistant"); ?>',
	'fi_at_sign': 			'<?php _e("At Sign","fp-foundation-assistant"); ?>',
	'fi_asterisk': 			'<?php _e("Asterisk","fp-foundation-assistant"); ?>',
	'fi_asl': 				'<?php _e("ASL","fp-foundation-assistant"); ?>',
	'fi_arrows_out': 		'<?php _e("Arrows Out","fp-foundation-assistant"); ?>',
	'fi_arrows_in': 		'<?php _e("Arrows In","fp-foundation-assistant"); ?>',
	'fi_arrows_expand': 	'<?php _e("Arrows Expand","fp-foundation-assistant"); ?>',
	'fi_arrows_compress': 	'<?php _e("Arrows Compress","fp-foundation-assistant"); ?>',
	'fi_arrow_up': 			'<?php _e("Arrow Up","fp-foundation-assistant"); ?>',
	'fi_arrow_right': 		'<?php _e("Arrow Right","fp-foundation-assistant"); ?>',
	'fi_arrow_left': 		'<?php _e("Arrow Left","fp-foundation-assistant"); ?>',
	'fi_arrow_down': 		'<?php _e("Arrow Down","fp-foundation-assistant"); ?>',
	'fi_archive': 			'<?php _e("Archive","fp-foundation-assistant"); ?>',
	'fi_annotate': 			'<?php _e("Annotate","fp-foundation-assistant"); ?>',
	'fi_anchor': 			'<?php _e("Anchor","fp-foundation-assistant"); ?>',
	'fi_align_right': 		'<?php _e("Align Right","fp-foundation-assistant"); ?>',
	'fi_align_left': 		'<?php _e("Align Left","fp-foundation-assistant"); ?>',
	'fi_align_justify': 	'<?php _e("Align Justify","fp-foundation-assistant"); ?>',
	'fi_alert': 			'<?php _e("Alert","fp-foundation-assistant"); ?>',
	'fi_address_book': 		'<?php _e("Address Book","fp-foundation-assistant"); ?>'

};
</script>

    <?php

}


















